export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK ="DELETE_TASK";
export const FILTER_TASK ="FILTER_TASK";
export const CLEAR_FILTER_TASK="CLEAR_FILTER_TASK";
export const SET_CURRENT_TASK ="SET_CURRENT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";
export const CHANGE_STATUS_TASK = "CHANGE_STATUS_TASK";